# Generated by Django 4.0.6 on 2022-07-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='path_and_name', verbose_name='Profile Picture'),
        ),
    ]
