# Generated by Django 4.0.6 on 2022-07-25 12:14

import app_users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_user_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to=app_users.models.path_and_name, verbose_name='Profile Picture'),
        ),
    ]
